In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
class Logistic:
    def __init__(self,learning_rate=0.01,epochs=100):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weight = None
        self.bias = None
        
    # sigmoid fun
    def sigmoid(self,z):
        return 1 / (1 + np.exp(-z))

    def fit(self,X,y):
        n_samples,n_features = X.shape
        
        self.weight = np.zeros(n_features)
        self.bias = 0
        
        # gradient decent
        for i in range(self.epochs):
            
            z = np.dot(X,self.weight) + self.bias
            
            y_pred = self.sigmoid(z)
            
            dw = (1/n_samples) * np.dot(X.T,(y_pred - y))
            db = (1/n_samples) * np.sum(y_pred - y)
            
            
            self.weight = self.weight - self.learning_rate * dw
            self.bias = self.bias - self.learning_rate * db
        
        self.coef_ = self.weight.reshape(1, -1)
        self.intercept_ = np.array([self.bias])
    
              
    # def predict(self,X):
    #     lin = np.dot(X, self.weight) + self.bias
    #     prob = self.sigmoid(lin)
        
    #     if(prob >= 0.5): return 1
        
    #     return 0   
    
    
    def predict_proba(self, X):
        linear = np.dot(X, self.weight) + self.bias
        return self.sigmoid(linear)

    def predict(self, X):
        probabilities = self.predict_proba(X)
        return np.where(probabilities >= 0.5, 1, 0)
        
             

In [130]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [131]:
df = pd.read_csv("../data/process_classification_data.csv")

In [132]:
df = df.iloc[0:,1:]

In [133]:
df.head(2)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,1,-0.948880,-0.945448,0.274814,0.228446,-1.699001,0
1,0,-0.898767,-0.877932,-0.827242,0.621715,-1.651815,0


In [134]:
X = df.drop(columns=['Machine failure'],axis=1)
y = df['Machine failure']

In [135]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10,stratify=y)

In [136]:
model = LogisticRegression(max_iter=1000)

In [137]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [138]:
print("SkLearn Coef = ",model.coef_)
print("SkLearn Intercept = ",model.intercept_)

SkLearn Coef =  [[-0.33469577  1.7850361  -1.18594783 -0.39456696  1.32231424  0.97852301]]
SkLearn Intercept =  [-5.27133539]


In [139]:
model.predict_proba(X_test)

array([[8.10568316e-01, 1.89431684e-01],
       [9.98901508e-01, 1.09849187e-03],
       [9.99846055e-01, 1.53945439e-04],
       ...,
       [8.19314616e-01, 1.80685384e-01],
       [9.92769398e-01, 7.23060169e-03],
       [9.99900232e-01, 9.97684086e-05]])

In [140]:
# my Class Logistic

myModel = Logistic(0.01,100)


In [141]:
myModel.fit(X_train,y_train)

In [142]:
predictions = myModel.predict(X_test)

In [143]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [144]:
model.intercept_

array([-5.27133539])

In [145]:
myModel.intercept_

array([-0.40722522])

In [146]:
model.coef_

array([[-0.33469577,  1.7850361 , -1.18594783, -0.39456696,  1.32231424,
         0.97852301]])

In [147]:
myModel.coef_

array([[-0.19776563,  0.01479229,  0.00715062, -0.01907313,  0.02670421,
         0.01588697]])